# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#00bcbc" } # cyan.regular

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b1a600", bold = true, italic = true, underline = true } # yellow.regular
find_position = { fg = "#d27bd8", bg = "reset", bold = true, italic = true } # magenta.regular

# Marker
marker_copied   = { fg = "#46bc69", bg = "#46bc69" } # green.regular
marker_cut      = { fg = "#f5746d", bg = "#f5746d" } # red.regular
marker_marked   = { fg = "#00bcbc", bg = "#00bcbc" } # cyan.regular
marker_selected = { fg = "#b1a600", bg = "#b1a600" } # yellow.regular

# Count
count_copied   = { fg = "#010408", bg = "#46bc69" } # blue.darkest, green.regular
count_cut      = { fg = "#010408", bg = "#f5746d" } # blue.darkest, red.regular
count_selected = { fg = "#010408", bg = "#b1a600" } # blue.darkest, yellow.regular

# Border
border_symbol = "│"
border_style  = { fg = "#636363" } # dimmed

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#010408", bg = "#32a9fe", bold = true } # blue.darkest, blue.regular
inactive = { fg = "#32a9fe", bg = "#0f304a" } # blue.regular, blue.darker

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#010408", bg = "#32a9fe", bold = true } # blue.darkest, blue.regular
normal_alt  = { fg = "#32a9fe", bg = "#0f304a" } # blue.regular, blue.darker

# Select mode
select_main = { fg = "#010408", bg = "#00bcbc", bold = true } # blue.darkest, cyan.regular
select_alt  = { fg = "#00bcbc", bg = "#0f304a" } # cyan.regular, blue.darker

# Unset mode
unset_main = { fg = "#010408", bg = "#f69b94", bold = true } # blue.darkest, red.light
unset_alt  = { fg = "#f69b94", bg = "#0f304a" } # red.light, blue.darker

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#636363" } # dimmed
perm_type  = { fg = "#32a9fe" } # blue.regular
perm_read  = { fg = "#b1a600" } # yellow.regular
perm_write = { fg = "#f5746d" } # red.regular
perm_exec  = { fg = "#46bc69" } # green.regular

# Progress
progress_label  = { fg = "#e4f0fb", bold = true } # blue.lightest
progress_normal = { fg = "#46bc69", bg = "#1f689d" } # green.regular, blue.dark
progress_error  = { fg = "#b1a600", bg = "#f5746d" } # yellow.regular, red.regular

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#32a9fe" } # blue.regular
active   = { fg = "#d27bd8", bold = true } # magenta.regular
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#32a9fe" } # blue.regular
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#32a9fe" } # blue.regular

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#32a9fe" } # blue.regular
title   = {}
hovered = { fg = "#d27bd8", bold = true } # magenta.regular

# : }}}


# : Which {{{

[which]
mask            = { bg = "#0f304a" } # blue.darker
cand            = { fg = "#00bcbc" } # cyan.regular
rest            = { fg = "#636363" } # dimmed
desc            = { fg = "#d27bd8" } # magenta.regular
separator       = "  "
separator_style = { fg = "#1f689d" } # blue.dark

# : }}}


# : Help {{{

[help]
on      = { fg = "#00bcbc" } # cyan.regular
run     = { fg = "#d27bd8" } # magenta.regular
hovered = { reversed = true, bold = true }
footer  = { fg = "#0f304a", bg = "#e4f0fb" } # blue.darker, blue.lightest

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#32a9fe" } # blue.regular
title    = { fg = "#32a9fe" } # blue.regular
tbl_col  = { fg = "#00bcbc" } # cyan.regular
tbl_cell = { fg = "#d27bd8", bg = "#1f689d" } # magenta.regular, blue.dark

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#46bc69" } # green.regular
title_warn  = { fg = "#b1a600" } # yellow.regular
title_error = { fg = "#f5746d" } # red.regular

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#00bcbc" }, # cyan.regular
	# Media
	{ mime = "{audio,video}/*", fg = "#b1a600" }, # yellow.regular
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d27bd8" }, # magenta.regular
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#46bc69" }, # green.regular
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#636363" }, # dimmed
	# Fallback
	{ url = "*", fg = "#e4f0fb" }, # blue.lightest
	{ url = "*/", fg = "#32a9fe" }, # blue.regular
	# TODO: remove
	{ name = "*", fg = "#e4f0fb" }, # blue.lightest
	{ name = "*/", fg = "#32a9fe" } # blue.regular
]

# : }}}
